# Generated by Django 6.0.3 on 2026-04-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('but', models.CharField(choices=[('Technique', 'Technique'), ('Endurance', 'Endurance'), ('Puissance', 'Puissance'), ('Grimpe libre', 'Grimpe Libre')])),
                ('description', models.CharField(max_length=400)),
                ('nombre_exercices', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programmeechauffement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prénom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Activité',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('date', models.DateField(auto_now_add=True)),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monapp.programme')),
                ('utilisateur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monapp.utilisateur')),
            ],
        ),
    ]
