# Generated by Django 6.0.3 on 2026-04-03 13:28

import datetime
import monapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activité',
            name='durée',
            field=models.DurationField(default=datetime.timedelta(seconds=10800), validators=[monapp.models.validate_max_duration]),
        ),
        migrations.AddField(
            model_name='programme',
            name='durée',
            field=models.DurationField(default=datetime.timedelta(seconds=7200), validators=[monapp.models.validate_max_duration]),
        ),
    ]
