# Generated by Django 6.0.4 on 2026-05-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
