# Generated by Django 6.0.4 on 2026-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_utilisateur_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Photo de profil'),
        ),
    ]
