# Generated by Django 6.0.3 on 2026-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_activité_durée_programme_durée'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeechauffement',
            name='titre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activité',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='programmeechauffement',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
