# Generated by Django 6.0.4 on 2026-06-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_alter_utilisateur_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo de profil'),
        ),
    ]
