# Generated by Django 6.0.3 on 2026-04-06 13:47

import datetime
import django.db.models.deletion
import monapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_programmeechauffement_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activité',
            name='but',
            field=models.CharField(choices=[('Technique', 'Technique'), ('Endurance', 'Endurance'), ('Puissance', 'Puissance'), ('Grimpe libre', 'Grimpe Libre')], default='Grimpe libre'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='but',
            field=models.CharField(choices=[('Technique', 'Technique'), ('Endurance', 'Endurance'), ('Puissance', 'Puissance'), ('Autre', 'Autre')]),
        ),
        migrations.CreateModel(
            name='ProgrammeCréé',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('but', models.CharField(choices=[('Technique', 'Technique'), ('Endurance', 'Endurance'), ('Puissance', 'Puissance'), ('Autre', 'Autre')])),
                ('description', models.CharField(max_length=400)),
                ('nombre_exercices', models.IntegerField(null=True)),
                ('durée', models.DurationField(default=datetime.timedelta(seconds=7200), validators=[monapp.models.validate_max_duration])),
                ('utilisateur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monapp.utilisateur')),
            ],
        ),
    ]
