# Generated by Django 6.0.3 on 2026-04-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0004_activité_but_alter_programme_but_programmecréé'),
    ]

    operations = [
        migrations.AddField(
            model_name='activité',
            name='programmecréé',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monapp.programmecréé'),
        ),
    ]
