# Generated by Django 6.0.4 on 2026-06-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0005_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='utilisateur_id',
            new_name='utilisateur',
        ),
    ]
