# Generated by Django 6.0.3 on 2026-04-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0005_activité_programmecréé'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activité',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monapp.programme'),
        ),
        migrations.AlterField(
            model_name='activité',
            name='programmecréé',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monapp.programmecréé'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='nombre_exercices',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programmecréé',
            name='nombre_exercices',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
