# Generated by Django 6.0.3 on 2026-04-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0006_alter_activité_programme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
