# Generated by Django 6.0.4 on 2026-04-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0007_alter_programme_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activité',
            name='programmecréé',
        ),
        migrations.AddField(
            model_name='programme',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monapp.utilisateur'),
        ),
        migrations.DeleteModel(
            name='ProgrammeCréé',
        ),
    ]
