# Generated by Django 6.0.4 on 2026-04-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0008_remove_activité_programmecréé_programme_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activité',
            name='but',
            field=models.CharField(choices=[('Technique', 'Technique'), ('Endurance', 'Endurance'), ('Puissance', 'Puissance'), ('Autre', 'Autre'), ('Grimpe libre', 'Grimpe Libre')], default='Grimpe libre'),
        ),
    ]
